// File generated by FlutterFire CLI.
// This is a placeholder - run: flutterfire configure to generate
// To get Firebase options, visit: https://firebase.google.com/

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADeQs6pL5tk4ThpIEWZnZdo7vcmwkZUQ8',
    appId: '1:422616326742:web:69249ff2d275ddf862d1f7',
    messagingSenderId: '422616326742',
    projectId: 'notes-assigment-whatbytes',
    authDomain: 'notes-assigment-whatbytes.firebaseapp.com',
    storageBucket: 'notes-assigment-whatbytes.firebasestorage.app',
    measurementId: 'G-2L6G3P1CHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2sNO_Q4-SvCA-ziSaESG5BMZj9GM1OYQ',
    appId: '1:422616326742:android:5c708074920d67fc62d1f7',
    messagingSenderId: '422616326742',
    projectId: 'notes-assigment-whatbytes',
    storageBucket: 'notes-assigment-whatbytes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Vh4peiIHaypSQCIpcKqh17jhuvfG6Ag',
    appId: '1:422616326742:ios:c3045b206c8048f162d1f7',
    messagingSenderId: '422616326742',
    projectId: 'notes-assigment-whatbytes',
    storageBucket: 'notes-assigment-whatbytes.firebasestorage.app',
    iosBundleId: 'com.example.notesAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemo-macOS-Key-Replace-With-Your-Own',
    appId: '1:123456789:macos:abcdef',
    messagingSenderId: '123456789',
    projectId: 'task-manager-demo',
    storageBucket: 'task-manager-demo.appspot.com',
    iosBundleId: 'com.example.notesAssignment',
  );
}